site_name: {{cookiecutter.project_name}}
repo_url: https://github.com/partsnap/{{cookiecutter.project_name}}
site_url: https://partsnap.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: partsnap/{{cookiecutter.project_name}}
copyright: 2024 PartSnap LLC.
dev_addr: 127.0.0.1:{{cookiecutter.mkdocs_port}}
nav:
  - Home: index.md
  {% if cookiecutter.database == "y" -%}
  - Docker: docker.md
  {%- endif %}
plugins:
  - search
  - drawio_file
  - mermaid2:
      version: 10.2.4
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            inherited_members: false
            annotations_path: brief
            show_signature: true
            modernize_annotations: true
            show_signature_annotations: true
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/partsnap/{{cookiecutter.project_name}}
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.project_name}}

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
